Add wandb resume argument
aicip/SatMAE pull request #26
Opened 2023-03-09 19:49 UTC by drkostas

https://docs.wandb.ai/guides/runs/resuming

For graph consistency

2023-03-09 19:53 UTC, andreicozma1 requested changes

2023-03-09 19:53 UTC, andreicozma1 commented on main_pretrain.py
> +    )
oh didn't see the PR marked as draft till I refreshed the page

2023-03-09 19:54 UTC, drkostas commented on main_pretrain.py
> +    )
Haha yes still working on it

2023-03-10 04:36 UTC, andreicozma1 commented on main_pretrain.py
> +            wandb.config.update(wandb_args, allow_val_change=True)
nice!

2023-03-10 04:36 UTC, andreicozma1 approved these changes
All looks good! no questions from my side

2023-03-10 05:57 UTC, maofengggg approved these changes
coool!

2023-03-10 13:41 UTC, merged